### ISSUE TITLE
Error on delete

### ISSUE THREAD

**Issue by danhowellnz** [douglascayers/sfdc-preserve-chatter-files-on-merge#3]
Hi Doug, 

I installed this on the development org but never tried it out. It seemed something good to have running in the background. I hit this when deleting a person account:

Validation Errors While Saving Record(s)
--
There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dca_merge_files.AccountMergeTrigger caused an unexpected exception, contact your administrator: dca_merge_files.AccountMergeTrigger: execution of AfterDelete caused by: System.QueryException: Implementation restriction: ContentDocumentLink requires a filter by a single Id on ContentDocumentId or LinkedEntityId using the equals operator or multiple Id's using the IN operator.: (dca_merge_files)".

Couldn't see anything in the logs that was useful.

**Comment by douglascayers** [comment]
Thanks for the details. I've not tried with Person Accounts before. Will try to take a look soon.

**Comment by douglascayers** [comment]
Hi @danhowellnz,

I've released new version **1.3** that I think resolves the Person Account issue. I don't have access to an org with Person Accounts, but based on the error message I've added some conditions to avoid querying `ContentDocumentLink` if the set of record ids is empty.

Please check the new version out and let me know if this resolves your issue.

  * [Production URL](https://login.salesforce.com/packaging/installPackage.apexp?p0=04tf40000008Ti2)
  * [Sandbox URL](https://test.salesforce.com/packaging/installPackage.apexp?p0=04tf40000008Ti2)

Thanks!

Doug
