### ISSUE TITLE
Test class failing

### ISSUE THREAD

**Issue by kbannon346** [douglascayers/sfdc-preserve-chatter-files-on-merge#7]
Seems like the test_merge_accounts_trigger_enabled() test method is failing in the SObjectFileMergeTriggerHandlerTests class.

Error is Document with ID: xx is already linked with the entity with ID xx

Anyone else having this issue?

**Comment by douglascayers** [comment]
Thanks for the feedback @kbannon346. I haven't had a chance to look into this yet, will try to get to it soon.

**Comment by douglascayers** [comment]
According to [this thread](https://success.salesforce.com/_ui/core/userprofile/UserProfilePage?u=00530000006aZOA&tab=sfdc.ProfilePlatformFeed&fId=0D53A00002uKsks), Neil Hayek, a Salesforce Engineer on the Files team, says that Summer '18 now solves this issue natively on the platform.

That would mean using this app would then conflict and duplicate the now native behavior resulting in the error you saw that the file had already been linked to the new master record.

We are waiting on the release notes to be updated to reflect this new behavior.

**Comment by douglascayers** [comment]
I've updated the project's README with note about the Summer '18 release notes: http://docs.releasenotes.salesforce.com/en-us/summer18/release-notes/rn_files_merge_records.htm#rn_files_merge_records
